--
-- Initial bootstrap wizard (Task 36).
--
-- Used when an operator points a fresh instance at an empty etcd
-- prefix: the SPA's /bootstrap page asks for a cluster name and a
-- template, the resolver renders a starter YAML, validates it
-- against the live `config:jsonschema()`, and writes it through the
-- two-phase pipeline (etcd if configured, dry-run otherwise).
--
-- The module is pure data + helpers; the GraphQL resolver supplies
-- the etcd client and persistence side-effects. Keeping it side-
-- effect-free makes the templates unit-testable without spinning a
-- real Tarantool process.
--

local M = {}

-- ── Helpers ──────────────────────────────────────────────────────────

local function indent(level)
    return string.rep('  ', level)
end

-- Stable credentials block. webui_peer is the system account used
-- by net.box pool authentication; admin_dev / operator_dev /
-- viewer_dev / superuser_dev mirror the dev compose fixtures so a
-- fresh deploy has a way to log in. Operators are expected to
-- rotate these immediately via roles_cfg.webui.rbac.users + a
-- secrets manager.
local function credentials_block()
    return table.concat({
        'credentials:',
        indent(1) .. 'users:',
        indent(2) .. 'replicator:',
        indent(3) .. 'password: \'replicator-password\'',
        indent(3) .. 'roles: [replication]',
        indent(2) .. 'webui_peer:',
        indent(3) .. 'password: \'webui-peer-password\'',
        indent(3) .. 'roles: [super]',
        indent(2) .. 'admin_dev:',
        indent(3) .. 'password: \'admin-dev-password\'',
        indent(3) .. 'roles: [super]',
        indent(2) .. 'operator_dev:',
        indent(3) .. 'password: \'operator-dev-password\'',
        indent(3) .. 'roles: [public]',
        indent(2) .. 'viewer_dev:',
        indent(3) .. 'password: \'viewer-dev-password\'',
        indent(3) .. 'roles: [public]',
        indent(2) .. 'superuser_dev:',
        indent(3) .. 'password: \'superuser-dev-password\'',
        indent(3) .. 'roles: [public]',
    }, '\n')
end

local function roles_block()
    return 'roles: [webui]\n'
        .. 'roles_cfg:\n'
        .. indent(1) .. 'webui:\n'
        .. indent(2) .. 'listen: \'0.0.0.0:8081\'\n'
        .. indent(2) .. 'log_level: info'
end

local function instance(name, iproto_port)
    return indent(5) .. name .. ':\n'
        .. indent(6) .. 'iproto:\n'
        .. indent(7) .. 'listen:\n'
        .. indent(8) .. '- uri: \'0.0.0.0:' .. tostring(iproto_port) .. '\''
end

-- ── Templates ────────────────────────────────────────────────────────

-- Each template returns a YAML body. The cluster_name parameter
-- shapes the iproto advertise prefix and naming. Templates are
-- intentionally minimal: they boot a working cluster and leave the
-- operator to specialise (memtx tuning, vshard groups, mTLS).

local function tpl_single(_cluster_name)
    return table.concat({
        '#',
        '# Single-instance bootstrap template.',
        '# Generated by /bootstrap. Customize before production.',
        '#',
        credentials_block(),
        '',
        'iproto:',
        indent(1) .. 'advertise:',
        indent(2) .. 'peer:',
        indent(3) .. 'login: webui_peer',
        '',
        'replication:',
        indent(1) .. 'failover: off',
        '',
        'groups:',
        indent(1) .. 'default:',
        indent(2) .. 'replicasets:',
        indent(3) .. 'rs-1:',
        indent(4) .. 'instances:',
        instance('inst-1', 3301),
        '',
        roles_block(),
        '',
    }, '\n')
end

local function tpl_replicaset_3(_cluster_name)
    return table.concat({
        '#',
        '# Three-instance replicaset with raft election.',
        '# Generated by /bootstrap. Customize before production.',
        '#',
        credentials_block(),
        '',
        'iproto:',
        indent(1) .. 'advertise:',
        indent(2) .. 'peer:',
        indent(3) .. 'login: webui_peer',
        '',
        'replication:',
        indent(1) .. 'failover: election',
        '',
        'groups:',
        indent(1) .. 'default:',
        indent(2) .. 'replicasets:',
        indent(3) .. 'rs-1:',
        indent(4) .. 'instances:',
        instance('inst-1', 3301),
        instance('inst-2', 3302),
        instance('inst-3', 3303),
        '',
        roles_block(),
        '',
    }, '\n')
end

local function tpl_vshard_3x3(_cluster_name)
    -- Skeleton only. A full vshard topology needs sharding.bucket_count
    -- and per-instance roles; ship the most common 3-router/3-storage
    -- layout as a starting point. Operators tune bucket counts.
    return table.concat({
        '#',
        '# Vshard 3x3 (three storage replicasets + routers).',
        '# Generated by /bootstrap. Customize before production.',
        '#',
        credentials_block(),
        '',
        'iproto:',
        indent(1) .. 'advertise:',
        indent(2) .. 'peer:',
        indent(3) .. 'login: webui_peer',
        '',
        'replication:',
        indent(1) .. 'failover: election',
        '',
        'sharding:',
        indent(1) .. 'bucket_count: 3000',
        '',
        'groups:',
        indent(1) .. 'storages:',
        indent(2) .. 'sharding: { roles: [storage] }',
        indent(2) .. 'replicasets:',
        indent(3) .. 'storage-1:',
        indent(4) .. 'instances:',
        instance('storage-1-a', 3301),
        indent(3) .. 'storage-2:',
        indent(4) .. 'instances:',
        instance('storage-2-a', 3302),
        indent(3) .. 'storage-3:',
        indent(4) .. 'instances:',
        instance('storage-3-a', 3303),
        indent(1) .. 'routers:',
        indent(2) .. 'sharding: { roles: [router] }',
        indent(2) .. 'replicasets:',
        indent(3) .. 'router-1:',
        indent(4) .. 'instances:',
        instance('router-1-a', 3311),
        '',
        roles_block(),
        '',
    }, '\n')
end

M.TEMPLATES = {
    {
        name        = 'single-instance',
        title       = 'Single instance',
        description = 'One Tarantool process, no replication. Good for evaluation.',
        render      = tpl_single,
    },
    {
        name        = 'replicaset-3',
        title       = 'Three-instance replicaset',
        description = 'Raft election, one writer, two replicas. Production baseline.',
        render      = tpl_replicaset_3,
    },
    {
        name        = 'vshard-3x3',
        title       = 'Vshard cluster (3 storages + router)',
        description = 'Sharded layout skeleton; tune bucket counts before deploy.',
        render      = tpl_vshard_3x3,
    },
}

local function find_template(name)
    for _, t in ipairs(M.TEMPLATES) do
        if t.name == name then return t end
    end
    return nil
end

function M.list_templates()
    local out = {}
    for _, t in ipairs(M.TEMPLATES) do
        table.insert(out, {
            name        = t.name,
            title       = t.title,
            description = t.description,
        })
    end
    return out
end

-- Render a template by name. Returns (yaml, nil) on success, or
-- (nil, err_code) for an unknown template. Cluster name is
-- whitelist-validated to keep the YAML deterministic and to avoid
-- injection — the wizard inserts it into a comment header only.
function M.render(template_name, cluster_name)
    local tpl = find_template(template_name)
    if tpl == nil then
        return nil, 'TEMPLATE_NOT_FOUND'
    end
    if cluster_name ~= nil and type(cluster_name) ~= 'string' then
        return nil, 'INVALID_CLUSTER_NAME'
    end
    if cluster_name ~= nil
        and not cluster_name:match('^[%w][%w_%-%.]*$') then
        return nil, 'INVALID_CLUSTER_NAME'
    end
    return tpl.render(cluster_name)
end

-- ── status ──────────────────────────────────────────────────────────

-- Decide whether the bootstrap wizard should kick in. The decision
-- is intentionally conservative: a positive `needed=true` only when
-- BOTH the local config source is empty AND the etcd probe (when
-- configured) returns no `config` key. Any ambiguity returns
-- `needed=false` so the wizard never overwrites a live deployment.
--
-- Returns: { needed = bool, reason = string, source = "etcd"|"file"|"unknown" }
function M.status(opts)
    opts = opts or {}
    local local_yaml = opts.local_yaml
    local etcd       = opts.etcd_client

    if etcd ~= nil then
        local existing, _err = etcd:get('config')
        if existing ~= nil and existing.value ~= nil
            and #existing.value > 0 then
            return {
                needed = false,
                source = 'etcd',
                reason = 'etcd already holds a config key',
            }
        end
        -- existing == nil: get() returned nil — could be KEY_NOT_FOUND
        -- (good) or a transport error (ambiguous). Defer to the file
        -- check below; the operator sees the explicit reason text.
    end

    if local_yaml ~= nil and #local_yaml > 0 then
        return {
            needed = false,
            source = 'file',
            reason = 'local cluster.yaml is non-empty',
        }
    end

    return {
        needed = true,
        source = etcd ~= nil and 'etcd' or 'unknown',
        reason = 'no cluster config detected',
    }
end

return M
