-- Static file handler — serves the embedded SPA bundle.
--
-- The bundle is loaded once at module require time. Each request:
--   1. normalises the path (strip query/fragment, "/" → "/index.html")
--   2. looks up the canonical entry in the bundle table
--   3. falls back to /index.html for SPA history-mode paths
--   4. negotiates Content-Encoding (br > gz > raw) by Accept-Encoding
--   5. compares If-None-Match to the entry's ETag and emits 304 on hit
--   6. emits Cache-Control:
--        public, max-age=31536000, immutable  for content-hashed assets
--        no-cache, no-store, must-revalidate  for index.html / SPA paths
--
-- The handler must be wrapped via http.middleware.wrap before being
-- registered as a route so that request-id, security headers and
-- structured logging are applied uniformly with the rest of the API.

local log_util = require('webui.log_util')

local logger = log_util.with_tag('static')

-- Bundle is generated by `make embed-assets`. Loading is wrapped in
-- pcall so the role can still start (and serve /api/health) in unit-
-- test contexts where the bundle has not been produced yet.
local bundle
do
    local ok, mod = pcall(require, 'webui.assets.bundle')
    if ok then
        bundle = mod
    else
        bundle = {}
        logger.warn('asset bundle not available; UI will return 404', {
            err = tostring(mod),
        })
    end
end

local M = {}

local INDEX_PATH = '/index.html'

-- Path prefixes whose missing entries result in a hard 404, not an
-- SPA fallback. They cover static assets, the api surface and well-
-- known crawler endpoints, where "secretly serving the SPA" would
-- mask a real bug or break crawlers.
local NON_SPA_PREFIXES = {
    '/api/',
    '/admin/',
    '/ws',
    '/assets/',
    '/monacoeditorwork/',
    '/favicon.ico',
    '/robots.txt',
    '/sitemap.xml',
    '/.well-known/',
}

-- Path prefixes that produce content-hashed assets. Their immutability
-- is what makes year-long caching safe.
local IMMUTABLE_PREFIXES = {
    '/assets/',
    '/monacoeditorwork/',
}

local function has_prefix(path, prefix)
    return string.sub(path, 1, #prefix) == prefix
end

local function any_prefix(path, prefixes)
    for _, p in ipairs(prefixes) do
        if has_prefix(path, p) then return true end
    end
    return false
end

local function normalize_path(path)
    if type(path) ~= 'string' or path == '' then
        return INDEX_PATH
    end
    -- Strip query/fragment defensively; the http rock already does
    -- this for req.path but the handler must remain correct when
    -- called from tests with arbitrary inputs.
    local clean = string.match(path, '^([^?#]+)') or path
    if clean == '/' then
        return INDEX_PATH
    end
    return clean
end

local function cache_control_for(path)
    if any_prefix(path, IMMUTABLE_PREFIXES) then
        return 'public, max-age=31536000, immutable'
    end
    return 'no-cache, no-store, must-revalidate'
end

-- Pick the best available encoding given the client's Accept-Encoding.
-- We prefer brotli over gzip per RFC 7932 (size). q-values are not
-- honoured — every modern client we serve advertises br/gzip without
-- weighting them down, and parsing q-values is not worth the bytes.
local function pick_encoding(accept_enc, entry)
    if type(accept_enc) ~= 'string' or accept_enc == '' then
        return 'raw'
    end
    local lower = string.lower(accept_enc)
    if entry.body_br ~= nil and string.find(lower, 'br', 1, true) then
        return 'br'
    end
    if entry.body_gz ~= nil and string.find(lower, 'gzip', 1, true) then
        return 'gz'
    end
    return 'raw'
end

-- Build the success response (200) or the conditional response (304).
local function build_response(entry, encoding, if_none_match, path)
    if if_none_match ~= nil and if_none_match == entry.etag then
        return {
            status = 304,
            headers = {
                ['etag']          = entry.etag,
                ['cache-control'] = cache_control_for(path),
            },
        }
    end

    local body, size, content_encoding
    if encoding == 'br' then
        body, size, content_encoding = entry.body_br, entry.size_br, 'br'
    elseif encoding == 'gz' then
        body, size, content_encoding = entry.body_gz, entry.size_gz, 'gzip'
    else
        body, size = entry.body_raw, entry.size_raw
    end

    local headers = {
        ['content-type']   = entry.mime,
        ['content-length'] = tostring(size or #body),
        ['etag']           = entry.etag,
        ['cache-control']  = cache_control_for(path),
        ['vary']           = 'accept-encoding',
    }
    if content_encoding ~= nil then
        headers['content-encoding'] = content_encoding
    end

    return {
        status = 200,
        headers = headers,
        body = body,
    }
end

local function not_found_response()
    return {
        status = 404,
        headers = {
            ['content-type']  = 'text/plain; charset=utf-8',
            ['cache-control'] = 'no-cache',
        },
        body = 'Not Found',
    }
end

function M.handler(req)
    local path = normalize_path(req.path)
    local entry = bundle[path]
    local resolved = path
    local outcome = 'hit'

    if entry == nil then
        if any_prefix(path, NON_SPA_PREFIXES) then
            logger.debug('static miss (no spa fallback)', { path = path })
            return not_found_response()
        end
        -- SPA history-mode: serve index.html so the Vue router can
        -- pick up the route in the client.
        entry = bundle[INDEX_PATH]
        resolved = INDEX_PATH
        outcome = 'spa_fallback'
    end

    if entry == nil then
        -- Bundle never loaded (degraded mode).
        logger.warn('static handler hit with empty bundle', { path = path })
        return not_found_response()
    end

    local headers = req.headers or {}
    local accept_enc = headers['accept-encoding']
    local if_none_match = headers['if-none-match']
    local encoding = pick_encoding(accept_enc, entry)

    local response = build_response(entry, encoding, if_none_match, resolved)
    if response.status == 304 then
        outcome = '304'
    end

    logger.debug('static', {
        path = path,
        resolved = resolved,
        status = response.status,
        encoding = encoding,
        size = response.headers['content-length'],
        outcome = outcome,
    })

    return response
end

-- Module-level introspection. Useful for /api/health checks and tests.
function M.stats()
    local n = 0
    local total_raw = 0
    for _, entry in pairs(bundle) do
        n = n + 1
        total_raw = total_raw + (entry.size_raw or 0)
    end
    return {
        loaded = next(bundle) ~= nil,
        entries = n,
        total_raw_bytes = total_raw,
        index_present = bundle[INDEX_PATH] ~= nil,
    }
end

-- Exposed for tests.
M.INDEX_PATH = INDEX_PATH
M._bundle = bundle
M._normalize_path = normalize_path
M._pick_encoding = pick_encoding
M._cache_control_for = cache_control_for

return M
